apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ao3m2z2wd-java-springboot
  janus-idp.io/tekton: ao3m2z2wd-java-springboot
  backstage.io/kubernetes-id: ao3m2z2wd-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ao3m2z2wd-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
